version: '3.7'

networks:
  todolist_net:
    driver: bridge
    name: todolist_network

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=todolist
      - MYSQL_PASSWORD=todolist
      - TZ=Asia/Shanghai
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - todolist_net

  todolist-app:
    container_name: todolist-app
    image: hzhenj/todolist-server:latest
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    networks:
      - todolist_net

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - todolist_net