service:
  app_mode: release
  http_port: :3000

database:
  db_type: mysql
  user: todolist
  password: todolist
  host: mysql:3306
  db_name: todolist
  charset: utf8mb4
  parse_time: True
  loc: Local

redis:
  redis_debug: false
  redis_addr: redis:6379
  redis_pw:
  redis_db_name: 2